package:
  name: enaml-native-barcode
  version: 1.0.1

requirements:
  build:
    - python
  run:
    - enaml-native

build:
  number: 1
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: MIT